name: FRE-NCtools CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Container
      run: docker build . -t fre-nctools
    - name: Run Tests
      run: docker run -u root --entrypoint "/bin/sh" fre-nctools /build.sh
