# Github actions CI file
# Ryan Mulhall 2020
# Configures with and without mpi and runs make check
name: build_FRE-NCtools

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04	
    strategy:
      matrix:
        with_mpi: ['--with-mpi', '']
    env:
      MPI: ${{ matrix.with_mpi }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo add-apt-repository ppa:remik-ziemlinski/nccmp --update
          sudo apt-get install -y libnetcdf-dev libnetcdff-dev netcdf-bin libopenmpi-dev openmpi-bin bats nccmp
      - name: Build and test
        run: | 
          autoreconf -i configure.ac
          ./configure $MPI
          make -j check LOG_DRIVER_FLAGS=--comments
      - name: find file
        run: |
          find $GITHUB_WORKSPACE -name ocean_temp_salt.res.latlon.nc
      - name: Save log file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-suite${{ matrix.with_mpi}}.log
          path: $GITHUB_WORKSPACE/ocean_temp_salt.res.latlon.nc
