# Github actions CI file
# Ryan Mulhall 2020
# CI testing for the FRE-NCtools repo, builds and runs unit tests
# container @ https://hub.docker.com/repository/docker/noaagfdl/fre-nctools-base
name: FRE-NCtools CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        with_mpi: ['','--with-mpi']
        enable_quad_precision: ['', '--enable-quad-precision']
    container:
      image: noaagfdl/fre-nctools-base
      env:
        MPI: ${{ matrix.with_mpi }}
        QUAD_P: ${{ matrix.enable_quad_precision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: | 
        autoreconf -i configure.ac
        ./configure $MPI $QUAD_P
    - name: Build tools
      run: make
    - name: Run tests
      run: make -j check LOG_DRIVER_FLAGS=--comments
    - name: Save log file on failure
      uses: actions/upload-artifact@v2.2.1
      if: failure()
      with:
        name: test-suite.log
        path: t/test-suite.log
