# Github actions CI file
# Ryan Mulhall 2020
# Configures with and without mpi and runs make check
name: build_FRE-NCtools

on: [push, pull_request]
#strategy:
#  matrix:
#    with_mpi: ['--with-mpi', '']
#steps:
#  - uses: actions/checkout@v2
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{matrix.with_mpi }}
