# Github actions CI file
# Ryan Mulhall 2020
# Builds and runs make check in two containers, one with mpi, one without
name: FRE-NCtools CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        with_mpi: ['','--with-mpi']
    env:
        MPI: ${{ matrix.with_mpi }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container
      run: |
        if [[ "$MPI" != "" ]]; then sed -i 's/autoconf/autoconf libopenmpi-dev openmpi-bin/' Dockerfile; fi
        docker build . -t fre-nctools$MPI
    - name: Build and run tests
      run: docker run -u root --entrypoint "/bin/sh" --env MPI fre-nctools$MPI /build.sh
    - name: Copy log file
      if: failure()
      run: docker cp `docker ps -aqf "name=fre-nctools$MPI"`:t/test-suite.log t/test-suite.log
    - name: Save log file on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
          name: test-suite${{ matrix.with_mpi}}.log
          path: t/test-suite.log
