# Github actions CI file
# Ryan Mulhall 2020
# Configures with and without mpi and runs make check
name: 'build_FRE-NCtools'

description: 'Container action for FRE-NCtools'
author: 'Ryan Mulhall'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
