# Github actions CI file
# Ryan Mulhall 2020
# Configures with and without mpi and runs make check
name: build_FRE-NCtools

on: [push, pull_request]
jobs:
  build:
    runs:
      using: 'docker'
      image: 'Dockerfile'
    strategy:
      matrix:
        with_mpi: ['--with-mpi', '']
    env:
      MPI: ${{ matrix.with_mpi }}
    steps:
      - uses: actions/checkout@v2
