name: Create Release draft and upload dist
on: push
#  push: commented out for testing, release step needs a tag trigger
#    tags:
#      - 20*.* # TODO update in 75 years
#      - 20*.*.*

jobs:
  create-release-dist:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rem1776/fre-nctools:dist-test4
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure
      run: |
        dnf install -y nco which
        mkdir build && cd build
        autoreconf -i ../configure.ac
        ../configure
    - name: Build and create distribution
      run: |
        which a2x
        which asciidoc
        cd build
        make
        make distcheck
        make dist
    - name: Create release draft and upload dist files
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/fre-nctools-*.*.tar.gz
          build/fre-nctools-*.*.*.tar.gz
        draft: True
