name: Create Release draft and upload dist

on:
  push:
    tags:
      - 20*.* # TODO update in 75 years
      - 20*.*.*

jobs:
  create-release-dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies # no nccmp package, but this will still pass configure
      run: |
        sudo apt-get install -y nco which netcdf-bin libnetcdf-dev \
          libnetcdff-dev mpich gcc gfortran asciidoc docbook-xsl docbook-xml \
          python3 python3-numpy python3-pytest perl git make libtool autoconf 
    - name: Configure
      run: |
        mkdir build && cd build
        autoreconf -i ../configure.ac
        ../configure
    - name: Build and create distribution
      run: |
        which a2x
        which asciidoc
        cd build
        make
        make -k distcheck
        make dist
    - name: Create release draft and upload dist files
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/fre-nctools-*.*.tar.gz
          build/fre-nctools-*.*.*.tar.gz
        draft: True
